import { Inter } from 'next/font/google'
import './global.css';

const inter = Inter({ subsets: ["greek-ext"] })

export const metadata = {
  title: 'Next Auth System',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          {children}
      </body>
    </html>
  )
}
